apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  # TODO: Change this name and make sure everything still works
  name: rili-world-tls
spec:
  secretName: rili.world-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: rili.world
  dnsNames:
    - rili.world
    - www.rili.world
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - rili.world
          - www.rili.world