apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-multi-com-tls
spec:
  secretName: rili.world-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: rili.world.com
  dnsNames:
    - rili.world.com
    - www.rili.world.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - rili.world.com
          - www.rili.world.com